# Generated by Django 5.1.2 on 2025-02-20 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_carouselitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
